<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_getImplicitWaitTimeout</name>
   <tag></tag>
   <elementGuidId>619df5ff-ef7e-4f6f-8c5b-c9c668520683</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.member-name-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='method-summary-table.tabpanel']/div/div[5]/code/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;getImplicitWaitTimeout&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>24a848b2-5f60-4f8a-baf3-29a402d03ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#getImplicitWaitTimeout()</value>
      <webElementGuid>f93e9080-a5df-43a4-86ba-678ebe1347be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>member-name-link</value>
      <webElementGuid>831b2d01-9833-406f-959b-e8cbae3804bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>getImplicitWaitTimeout</value>
      <webElementGuid>5240ea66-26b0-49d6-ba74-da8cf13479ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;method-summary-table.tabpanel&quot;)/div[@class=&quot;summary-table three-column-summary&quot;]/div[@class=&quot;col-second even-row-color method-summary-table method-summary-table-tab2 method-summary-table-tab5&quot;]/code[1]/a[@class=&quot;member-name-link&quot;]</value>
      <webElementGuid>90c2aa28-cc6a-47da-b3bd-a7d4f205a120</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='method-summary-table.tabpanel']/div/div[5]/code/a</value>
      <webElementGuid>efc3485b-b0fe-4f79-b10c-b3be990616b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'getImplicitWaitTimeout')]</value>
      <webElementGuid>2a41b2c4-c04e-4d98-8a8b-c9ead6d3453d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/following::a[1]</value>
      <webElementGuid>216886b6-1224-4895-b62f-d3e6faad317a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[2]/preceding::a[1]</value>
      <webElementGuid>35272037-eccf-42de-b3d0-3d236a8a46f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='getImplicitWaitTimeout']/parent::*</value>
      <webElementGuid>0dbabe74-adc3-42ad-900a-9de07c53af35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#getImplicitWaitTimeout()')]</value>
      <webElementGuid>9fdd7bb4-9af5-4dfc-ba26-dcbabaf2f150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/code/a</value>
      <webElementGuid>2d118743-2df8-46a7-8457-86e6c0d06ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#getImplicitWaitTimeout()' and (text() = 'getImplicitWaitTimeout' or . = 'getImplicitWaitTimeout')]</value>
      <webElementGuid>fb8c5189-2855-4984-9c56-a088b1d9e160</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
