<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Streng vlaggenbeleid op Songfestival in_cd4202</name>
   <tag></tag>
   <elementGuidId>b7efef8b-cd23-4a5f-9629-f6c1147f0bcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='page-main-content']/div[2]/div[2]/div[2]/div[6]/div/div/ol/li[4]/article/a/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;“Na je training een pint drinken is het slechtste wat je kan doen”: wat eet je best voor en na een loopwedstrijd zoals 10 Miles? PREMIUM “Na je training een pint drinken is het slechtste wat je kan doen”: wat eet je best voor en na een loopwed­strijd zoals 10 Miles?&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b9b45845-20ed-47b3-88e7-c743d39e1b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>“Na je training een pint drinken is het slechtste wat je kan doen”: wat eet je best voor en na een loopwedstrijd zoals 10 Miles?</value>
      <webElementGuid>c0de8c31-c2a9-4f59-a829-937195447857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ankeiler__image</value>
      <webElementGuid>a10a784c-1321-4d5b-8e55-25a4c7df5313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.hln.be/NTg4NTI2MDBhNjBjYzBmYzE5YzAvZGlvLzI1NjIyMDQwMi9mb2N1cy1hbmQtZmlsbC8wLjUwLzAuNTAvNjY2LzQ5OQ/21042024-antwerpen-10-miles-the-antwerp-10-miles-2024-48ste-editie-leopold-de-waelplaats-stephanie-scheirlynck</value>
      <webElementGuid>7a119e5c-d53b-4c10-96c1-5d74d7ee1bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>31ef7148-21bc-4653-8a6e-06f1be59b37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>499</value>
      <webElementGuid>d3c3cac3-cee8-4975-b630-9005804c93de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://images.hln.be/NTg4NTI2MDBhNjBjYzBmYzE5YzAvZGlvLzI1NjIyMDQwMi9mb2N1cy1hbmQtZmlsbC8wLjUwLzAuNTAvNjY2LzQ5OQ/21042024-antwerpen-10-miles-the-antwerp-10-miles-2024-48ste-editie-leopold-de-waelplaats-stephanie-scheirlynck</value>
      <webElementGuid>a08ec0ff-e3ab-4de5-bfdd-905c038bf586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>666</value>
      <webElementGuid>13f72c06-41ce-46ed-944b-b03e98e85bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-main-content&quot;)/div[@class=&quot;page-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;col-wrapper has-grid-layout&quot;]/div[@class=&quot;container-col-holder is-primary-left&quot;]/div[@class=&quot;col col--primary&quot;]/div[@class=&quot;sixpack sixpack--9&quot;]/ol[@class=&quot;tile-grid&quot;]/li[@class=&quot;tile tile--4 tile-small-1x2 tile-medium-2x1 tile-large-2x1 tile-xlarge-2x1 tile-xxlarge-2x1&quot;]/article[@class=&quot;ankeiler ankeiler--picture&quot;]/a[@class=&quot;ankeiler__link&quot;]/div[@class=&quot;ankeiler__thumb&quot;]/picture[@class=&quot;ankeiler__image-wrapper&quot;]/img[@class=&quot;ankeiler__image&quot;]</value>
      <webElementGuid>3823441f-cc64-4d1c-ba0f-f1ca755c7440</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='page-main-content']/div[2]/div[2]/div[2]/div[6]/div/div/ol/li[4]/article/a/div/picture/img</value>
      <webElementGuid>bff0a217-0b6b-478a-ba05-cbae65adbe2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='“Na je training een pint drinken is het slechtste wat je kan doen”: wat eet je best voor en na een loopwedstrijd zoals 10 Miles?']</value>
      <webElementGuid>599816eb-591a-41d8-a742-c2abe7f1fb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/ol/li[4]/article/a/div/picture/img</value>
      <webElementGuid>5bdc37d5-4640-4a4b-b0a4-3471ac1f8ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '“Na je training een pint drinken is het slechtste wat je kan doen”: wat eet je best voor en na een loopwedstrijd zoals 10 Miles?' and @src = 'https://images.hln.be/NTg4NTI2MDBhNjBjYzBmYzE5YzAvZGlvLzI1NjIyMDQwMi9mb2N1cy1hbmQtZmlsbC8wLjUwLzAuNTAvNjY2LzQ5OQ/21042024-antwerpen-10-miles-the-antwerp-10-miles-2024-48ste-editie-leopold-de-waelplaats-stephanie-scheirlynck']</value>
      <webElementGuid>7d99e05c-1047-499b-8bcb-8ff0ab83a4d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
