<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Akkoord-ate-b82-18d</name>
   <tag></tag>
   <elementGuidId>da232919-9fd3-4360-ad50-db3c8dc3efbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > #pg-modal > #pg-first-layer > #pg-footer > #pg-footer-content > #pg-accept-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pg-footer-content']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Akkoord&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>45666e38-91c0-496e-bd39-31e2458826ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pg-accept-btn</value>
      <webElementGuid>38862aa7-1f69-42d7-824f-46ffe31765d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pg-btn pg-btn-primary svelte-13hb02a</value>
      <webElementGuid>03400f09-9664-43ad-9eb1-12a983e99839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akkoord</value>
      <webElementGuid>041754ec-c610-4fcd-836f-36d291176773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[1]/div[@id=&quot;pg-modal&quot;]/div[@id=&quot;pg-first-layer&quot;]/footer[@id=&quot;pg-footer&quot;]/div[@id=&quot;pg-footer-content&quot;]/button[@id=&quot;pg-accept-btn&quot;]</value>
      <webElementGuid>0c154675-b6e8-4dfd-b03f-20b296773201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_DPG Media Privacy Gate/divpg-host-shadow-root-cy Gate-b82</value>
      <webElementGuid>3b75551d-1122-451c-934b-d6ff2bec5e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>257ce203-f2a8-408d-a965-67778a1b533d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pg-footer-content']/button</value>
      <webElementGuid>a4f36642-f2e2-4edf-9b5d-90717f1d326e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Akkoord']/parent::*</value>
      <webElementGuid>95cc085c-3e45-4c28-9fc7-71e9a279a0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pg-accept-btn' and (text() = 'Akkoord' or . = 'Akkoord')]</value>
      <webElementGuid>004d0109-e16d-4523-b9f4-709d7238db97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
