<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divpg-host-shadow-root-cy Gate-b82</name>
   <tag></tag>
   <elementGuidId>0c22ee92-1380-4198-a8ae-8c30354cced1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pg-host-shadow-root</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pg-host-shadow-root']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#pg-host-shadow-root</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2fc39a55-939c-48cd-a252-306b39999121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pg-host-shadow-root</value>
      <webElementGuid>989365ae-76ba-452e-925d-f73096ab8322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pg-host-shadow-root&quot;)</value>
      <webElementGuid>4767407c-c587-4b0c-a3ac-025d97b5fa2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pg-host-shadow-root']</value>
      <webElementGuid>4b8f20a2-8eba-4c90-b5d0-d3fb285b217e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]</value>
      <webElementGuid>b040ec77-d97f-4520-a10d-c66d9e3e0eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pg-host-shadow-root']</value>
      <webElementGuid>949a6d4d-9d3b-4955-8b51-e75d14e8e0a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
