<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WebDriver.Timeouts</name>
   <tag></tag>
   <elementGuidId>b8c449bd-63cc-40da-ac90-8ec1bbb3cbfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='class-summary.tabpanel']/div/div[159]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;WebDriver.Timeouts&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eac02a3b-87e3-4fd4-aecf-e7c68f0e3628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>WebDriver.Timeouts.html</value>
      <webElementGuid>5e343251-ec13-461f-91d8-74b5fda1ff9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>interface in org.openqa.selenium</value>
      <webElementGuid>ebbd82c9-83d4-47e2-8152-bb7a2339dd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WebDriver.Timeouts</value>
      <webElementGuid>ec16f465-b9ee-4778-89c3-e0c5e8d6d962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class-summary.tabpanel&quot;)/div[@class=&quot;summary-table two-column-summary&quot;]/div[@class=&quot;col-first class-summary class-summary-tab1 odd-row-color&quot;]/a[1]</value>
      <webElementGuid>9ddee199-9555-4ff4-be0e-a391b7764201</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='class-summary.tabpanel']/div/div[159]/a</value>
      <webElementGuid>5fd5ab42-42a3-4a8d-81ff-b145ac344f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'WebDriver.Timeouts')]</value>
      <webElementGuid>7de1cf7f-c06c-44c6-a828-55179c93a864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Used to locate a given frame or window.'])[1]/following::a[1]</value>
      <webElementGuid>02151201-9f76-4b24-92cb-012274cfe078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WebDriver.TargetLocator'])[1]/following::a[1]</value>
      <webElementGuid>ddbc0296-bf75-48ba-a9ef-3526b3a9b793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='An interface for managing timeout behavior for WebDriver instances.'])[1]/preceding::a[1]</value>
      <webElementGuid>ea7b733b-4d92-43b7-ad1a-41323ea44292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WebDriver.Window'])[1]/preceding::a[1]</value>
      <webElementGuid>14121d86-8ded-4a33-8d65-ca151d5d27f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WebDriver.Timeouts']/parent::*</value>
      <webElementGuid>bcc41fc4-2703-43e0-b6e6-6c9c02cb7486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'WebDriver.Timeouts.html')]</value>
      <webElementGuid>f129155c-bb7f-4264-993c-841e9e2c9d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[159]/a</value>
      <webElementGuid>b1b7e664-1dce-4bda-9c57-7b35ab7392b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'WebDriver.Timeouts.html' and @title = 'interface in org.openqa.selenium' and (text() = 'WebDriver.Timeouts' or . = 'WebDriver.Timeouts')]</value>
      <webElementGuid>768d4bbc-a417-4fba-8fd2-ab3c63f2179e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
