<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BrowsingContextInfo_1</name>
   <tag></tag>
   <elementGuidId>8819f712-9368-446c-8767-46fca978614d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='fromJson(org.openqa.selenium.json.JsonInput)']/div/span[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#method-detail div >> internal:has-text=&quot;public static BrowsingContextInfo fromJson(JsonInput input)&quot;i >> internal:attr=[title=&quot;class in org.openqa.selenium.bidi.browsingcontext&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>503a68be-48cf-49b3-82ab-5b6604dda01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>BrowsingContextInfo.html</value>
      <webElementGuid>9e81cf1c-e710-4d11-9583-b3dd0c0108b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.bidi.browsingcontext</value>
      <webElementGuid>ed9fa165-5ca6-44c6-8337-879d9bfe1e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BrowsingContextInfo</value>
      <webElementGuid>e9b5beea-0cdc-4d4b-95d3-e7db81fbf4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fromJson(org.openqa.selenium.json.JsonInput)&quot;)/div[@class=&quot;member-signature&quot;]/span[@class=&quot;return-type&quot;]/a[1]</value>
      <webElementGuid>89c221b7-85cd-4609-95d3-90133d4cebbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='fromJson(org.openqa.selenium.json.JsonInput)']/div/span[2]/a</value>
      <webElementGuid>c3699b10-e2a0-41bc-a025-fc17365762e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'BrowsingContextInfo')])[7]</value>
      <webElementGuid>65b461db-c4fb-4bb6-ade1-9d9a3659aa07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='public static'])[1]/following::a[1]</value>
      <webElementGuid>8849daea-c125-4966-99d8-925c1158e391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fromJson'])[2]/following::a[1]</value>
      <webElementGuid>d0d074b3-fae0-4ebb-8616-bda5dd788fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fromJson'])[3]/preceding::a[1]</value>
      <webElementGuid>4d31cfaf-b2ee-493a-94bd-77053334e08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'BrowsingContextInfo.html')])[7]</value>
      <webElementGuid>98cb0c22-32e7-4e2e-91ca-2a25d3348c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/section/div/span[2]/a</value>
      <webElementGuid>435fa6cd-985c-4dc7-902b-724282a3d94b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'BrowsingContextInfo.html' and @title = 'class in org.openqa.selenium.bidi.browsingcontext' and (text() = 'BrowsingContextInfo' or . = 'BrowsingContextInfo')]</value>
      <webElementGuid>46f5a49a-372a-45a9-b35a-5fa02857d093</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
