<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_fromJson</name>
   <tag></tag>
   <elementGuidId>fcb150e4-9570-4964-99ef-d3cef0a2f857</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-second.even-row-color.method-summary-table.method-summary-table-tab1.method-summary-table-tab4 > code > a.member-name-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='method-summary-table.tabpanel']/div/div[5]/code/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;fromJson&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>53dc15a7-ef90-4667-bcad-b1727711e105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#fromJson(org.openqa.selenium.json.JsonInput)</value>
      <webElementGuid>7c96ccce-eb8a-4a16-b9e1-35ce55a535cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>member-name-link</value>
      <webElementGuid>aed3fb9a-d604-4e41-b004-a4441aaf11b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>fromJson</value>
      <webElementGuid>3bc897b7-9ff2-47ef-84fa-4d131de15a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;method-summary-table.tabpanel&quot;)/div[@class=&quot;summary-table three-column-summary&quot;]/div[@class=&quot;col-second even-row-color method-summary-table method-summary-table-tab1 method-summary-table-tab4&quot;]/code[1]/a[@class=&quot;member-name-link&quot;]</value>
      <webElementGuid>2c20f654-d44a-436c-b545-3bf21ef9ac14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='method-summary-table.tabpanel']/div/div[5]/code/a</value>
      <webElementGuid>4418c74f-64cf-4576-88a7-f1a3c835de7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'fromJson')]</value>
      <webElementGuid>2c7ed094-17d0-45e6-9485-4fcc9ee8d9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BrowsingContextInfo'])[5]/following::a[1]</value>
      <webElementGuid>89bfcf91-08dd-42a2-979f-8d2c31657515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JsonInput'])[1]/preceding::a[1]</value>
      <webElementGuid>7a344a47-908b-491b-950f-a21772a1e5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='fromJson']/parent::*</value>
      <webElementGuid>e1444224-098f-41af-a585-cae54bb3fcc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#fromJson(org.openqa.selenium.json.JsonInput)')]</value>
      <webElementGuid>9d1acf8f-5edd-4155-a449-cbc0099dd6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/code/a</value>
      <webElementGuid>ec5fdf7f-f778-4845-a387-b21698ade544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#fromJson(org.openqa.selenium.json.JsonInput)' and (text() = 'fromJson' or . = 'fromJson')]</value>
      <webElementGuid>b1ef0249-c228-4e3d-8f17-433d6aba82c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
